volumes:
  cmd-stable:
  cmd-beta:
  stable:
  beta:

services:
  extractor-stable:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./data-stable:/opt/data
      - stable:/home/steam/Steam
      - cmd-stable:/home/steam/steamcmd
      - ./BepInEx:/opt/BepInEx
    entrypoint: ["/opt/run.sh", "public"]
  # extractor-beta:
  #   build:
  #     context: ./docker
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./data-beta:/opt/data
  #     - beta:/home/steam/Steam
  #     - cmd-beta:/home/steam/steamcmd
  #     - ./BepInEx:/opt/BepInEx
  #   entrypoint: ["/opt/run.sh", "beta"]
